# Generated by Django 4.0.3 on 2022-05-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlankInp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blankField', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeterReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_code', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('customer_id', models.IntegerField()),
                ('contact', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('house_no', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('citizenship', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('timestamp', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('reading_month', models.CharField(choices=[('January', 'January'), ('August', 'August'), ('February', 'February'), ('March', 'March'), ('October', 'October'), ('June', 'June'), ('December', 'December'), ('April', 'April'), ('July', 'July'), ('November', 'November'), ('May', 'May'), ('September', 'September')], max_length=10)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('previous_unit', models.IntegerField()),
                ('current_unit', models.IntegerField()),
                ('consumed_unit', models.IntegerField()),
                ('meter_status', models.CharField(blank=True, default='green', max_length=100, null=True)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
