# Generated by Django 3.2.3 on 2022-04-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('house_no', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('citizenship', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('reading_month', models.CharField(choices=[('September', 'September'), ('June', 'June'), ('March', 'March'), ('July', 'July'), ('January', 'January'), ('April', 'April'), ('May', 'May'), ('February', 'February'), ('August', 'August'), ('October', 'October'), ('December', 'December'), ('November', 'November')], max_length=10)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('previous_unit', models.IntegerField()),
                ('current_unit', models.IntegerField()),
                ('consumed_unit', models.IntegerField()),
                ('meter_status', models.CharField(blank=True, default='green', max_length=100, null=True)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
