# Generated by Django 3.2.3 on 2022-04-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='meter_status',
            field=models.CharField(default='green', max_length=100),
        ),
    ]
