# Generated by Django 3.2.3 on 2022-04-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reading_month',
            field=models.CharField(choices=[('May', 'May'), ('September', 'September'), ('October', 'October'), ('December', 'December'), ('February', 'February'), ('June', 'June'), ('July', 'July'), ('January', 'January'), ('March', 'March'), ('April', 'April'), ('August', 'August'), ('November', 'November')], max_length=10),
        ),
    ]
