# Generated by Django 3.2.3 on 2022-04-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0002_alter_payment_reading_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='subDate',
        ),
        migrations.AlterField(
            model_name='payment',
            name='reading_month',
            field=models.CharField(choices=[('December', 'December'), ('July', 'July'), ('January', 'January'), ('October', 'October'), ('September', 'September'), ('April', 'April'), ('February', 'February'), ('August', 'August'), ('March', 'March'), ('June', 'June'), ('May', 'May'), ('November', 'November')], max_length=10),
        ),
    ]
