# Generated by Django 3.2.3 on 2022-04-16 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0002_alter_payment_meter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reading_date',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reading_month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
