# Generated by Django 3.2.3 on 2022-04-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0003_auto_20220428_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlankInp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blankField', models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='reading_month',
            field=models.CharField(choices=[('October', 'October'), ('June', 'June'), ('April', 'April'), ('February', 'February'), ('November', 'November'), ('March', 'March'), ('August', 'August'), ('September', 'September'), ('May', 'May'), ('January', 'January'), ('December', 'December'), ('July', 'July')], max_length=10),
        ),
    ]
