# Generated by Django 3.2.3 on 2022-04-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0004_auto_20220418_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bill_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='current_unit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='penalty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='previous_unit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='saving_unit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_unit',
            field=models.IntegerField(),
        ),
    ]
