# Generated by Django 3.2.3 on 2022-04-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0004_auto_20220429_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blankinp',
            name='blankField',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reading_month',
            field=models.CharField(choices=[('January', 'January'), ('July', 'July'), ('March', 'March'), ('June', 'June'), ('November', 'November'), ('September', 'September'), ('December', 'December'), ('October', 'October'), ('February', 'February'), ('April', 'April'), ('May', 'May'), ('August', 'August')], max_length=10),
        ),
    ]
