# Generated by Django 3.2.3 on 2022-04-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0005_auto_20220418_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reading_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reading_month',
            field=models.IntegerField(),
        ),
    ]
