# Generated by Django 3.2.3 on 2022-04-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0006_auto_20220429_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reading_month',
            field=models.CharField(choices=[('January', 'January'), ('March', 'March'), ('December', 'December'), ('February', 'February'), ('August', 'August'), ('November', 'November'), ('April', 'April'), ('July', 'July'), ('September', 'September'), ('June', 'June'), ('October', 'October'), ('May', 'May')], max_length=10),
        ),
    ]
