# Generated by Django 3.2.3 on 2022-04-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0007_auto_20220422_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='meter_status',
            field=models.CharField(blank=True, default='green', max_length=100, null=True),
        ),
    ]
