# Generated by Django 3.2.3 on 2022-04-22 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0008_alter_payment_meter_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reading_date',
        ),
    ]
