# Generated by Django 4.0.4 on 2022-05-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0008_alter_payment_reading_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reading_month',
            field=models.CharField(choices=[('December', 'December'), ('June', 'June'), ('January', 'January'), ('October', 'October'), ('February', 'February'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('November', 'November'), ('March', 'March'), ('April', 'April'), ('May', 'May')], max_length=10),
        ),
    ]
