# Generated by Django 3.2.3 on 2022-04-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0009_remove_payment_reading_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reading_month',
            field=models.CharField(choices=[('June', 'June'), ('July', 'July'), ('April', 'April'), ('February', 'February'), ('October', 'October'), ('August', 'August'), ('May', 'May'), ('September', 'September'), ('December', 'December'), ('January', 'January'), ('November', 'November'), ('March', 'March')], max_length=10),
        ),
    ]
