# Generated by Django 3.2.3 on 2022-05-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0010_alter_payment_reading_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reading_month',
            field=models.CharField(choices=[('September', 'September'), ('June', 'June'), ('October', 'October'), ('November', 'November'), ('February', 'February'), ('August', 'August'), ('May', 'May'), ('April', 'April'), ('July', 'July'), ('December', 'December'), ('January', 'January'), ('March', 'March')], max_length=10),
        ),
    ]
