# Generated by Django 3.2.3 on 2022-04-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0011_auto_20220422_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='saving_unit',
            new_name='consumed_unit',
        ),
        migrations.AlterField(
            model_name='payment',
            name='reading_month',
            field=models.CharField(choices=[('February', 'February'), ('March', 'March'), ('July', 'July'), ('April', 'April'), ('May', 'May'), ('January', 'January'), ('September', 'September'), ('June', 'June'), ('October', 'October'), ('December', 'December'), ('August', 'August'), ('November', 'November')], max_length=10),
        ),
    ]
