# Generated by Django 3.2.3 on 2022-05-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0012_alter_payment_reading_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_code', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('customer_id', models.IntegerField()),
                ('contact', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='reading_month',
            field=models.CharField(choices=[('April', 'April'), ('October', 'October'), ('May', 'May'), ('September', 'September'), ('June', 'June'), ('August', 'August'), ('December', 'December'), ('July', 'July'), ('January', 'January'), ('March', 'March'), ('November', 'November'), ('February', 'February')], max_length=10),
        ),
    ]
