# Generated by Django 3.2.3 on 2022-04-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0012_auto_20220426_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reading_month',
            field=models.CharField(choices=[('October', 'October'), ('April', 'April'), ('July', 'July'), ('November', 'November'), ('June', 'June'), ('August', 'August'), ('January', 'January'), ('May', 'May'), ('September', 'September'), ('March', 'March'), ('February', 'February'), ('December', 'December')], max_length=10),
        ),
    ]
