# Generated by Django 3.2.3 on 2022-05-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0013_auto_20220506_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reading_month',
            field=models.CharField(choices=[('January', 'January'), ('April', 'April'), ('October', 'October'), ('August', 'August'), ('June', 'June'), ('March', 'March'), ('July', 'July'), ('November', 'November'), ('February', 'February'), ('May', 'May'), ('September', 'September'), ('December', 'December')], max_length=10),
        ),
    ]
