# Generated by Django 3.2.3 on 2022-05-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_profile_image_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
