# Generated by Django 3.2.3 on 2022-05-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
